<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HousingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingRepository extends EntityRepository
{
    public function findAllWaitingForReceipt() {
        $qb = $this->createQueryBuilder('h');
        $qb->where('h.tenant IS NOT NULL');

        return $qb->getQuery()->getResult();
    }
}
