<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends EntityRepository
{
    public function findReceiptForDate($housingId, $month, $year) {
        $start = \DateTime::createFromFormat('d-m-Y', '1-' . $month . '-' . $year);
        $start->setTime(0, 0, 0);

        $end = \DateTime::createFromFormat('d-m-Y', date('t', $start->getTimestamp()) . '-' . $month . '-' . $year);
        $end->setTime(23, 59, 59);

        $qb = $this->createQueryBuilder('r')
            ->where('r.housing = :housing')
            ->andWhere('r.date BETWEEN :dateStart AND :dateEnd')
            ->orderBy('r.date', 'DESC')
            ->setParameter(':housing', $housingId)
            ->setParameter(':dateStart', $start)
            ->setParameter(':dateEnd', $end)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
